### ISSUE TITLE
Uninstall Doesn't Work

### ISSUE THREAD

**Issue by Mango531** [itsmikethetech/Virtual-Display-Driver#103]
This is an FYI for the uninstall - I was having issues removing per the uninstall instructions, full description of issue below. The uninstall instructions worked once I removed the .inf / downloaded files from the original location they were placed to do the install. 

Issue:
I can uninstall the device from Device Manager > Display Adapters, but it comes right back. There is no new popup window with the 'Attempt to remove driver for this device' as mentioned in the uninstall instructions. 

Additionally, I can't delete from the pnputil command line. I receive an error, "Failed to delete driver package: One or more devices are presently installed using the specified INF".

**Comment by Mango531** [comment]
I wanted to remove this because I was having an issue with my dual monitor setup. One monitor is HDMI and the other is DP. The HDMI monitor is my primary and would only display my PC if the DP was also powered on. Once the virtual display adapter was removed, the monitor behavior returned to normal. 

Is this a known issue with the virtual display adapter?

**Comment by zjoasan** [comment]
I got it running on a dual display with out these issues (DP and VGA, only iGPU). But having a hard time uninstalling sounds a bit strange. What I always do is right click on VDD, disable device. then uninstall. With the device disabled I always get the "Also remove drivers" checkbox. But it removes them from windows, the actual files in "c:\IddSampleDriver" should not disappear, the have them removed require manually removal, for now. 

Regarding DP monitor having to be powered on for HDMI monitor to display, leads me to think they might be connected to different GPU's and DP being connected to iGPU? This should be corrected in next release, but right now VDD often attach to iGPU before Dedicated GPU, eg. "prioritize the iGPU" is the best way I would phrase it.

Hope this helps, work is being done on a installer.

**Comment by bud3699** [comment]
Are you perhaps removing the display instead of the display adapter ? Couple people have done the same thing

**Comment by kkota1** [comment]
@bud3699 that was my mistake, thanks

**Comment by sofmeright** [comment]
If there is interest I have been working on a [little tool](https://github.com/sofmeright/IDDSampleDriver_Wizard) that covers all the functionality that I am aware of in the mechanics involving setup of the display driver. If you want to toggle the driver installation it will do that quite easy, its one click. Hoping for a better solution as mine is currently ugly. But I'll still share 😅

**Comment by bud3699** [comment]
https://github.com/VirtualDisplay/Virtual-Display-Driver/wiki/Uninstalling-Virtual-Display-Driver

**Comment by funnymataleao** [comment]
> https://github.com/VirtualDisplay/Virtual-Display-Driver/wiki/Uninstalling-Virtual-Display-Driver

Thank you very much. It helps.
