### ISSUE TITLE
REQUEST: Add additional Resolution 2388 x 1668 120FPS

### ISSUE THREAD

**Issue by Dark1886** [itsmikethetech/Virtual-Display-Driver#107]
EDIT: I think I solved my problem by adding it to the Option.txt file. I'm not entirely certain if this fixed the issue or it was fixed when I changed the advertised resolutions in sunshine.

**Comment by bud3699** [comment]
Yeh, editing the options.txt will add/remove resolutions on driver initialise. SO disabling and enable the driver, uninstalling and installing or just restarting the device
