### ISSUE TITLE
Build guide? What IDE, what project structure, dependencies, etc?

### ISSUE THREAD

**Issue by Apprisco** [itsmikethetech/Virtual-Display-Driver#120]
Hey! 
I noticed there's no build guide for this project.
I'd like to build the beta as I have multiple NVIDIA gpus and it's not working with sunshine, but working with everything else.
Any ideas?

**Comment by zjoasan** [comment]
As soon as next release is done, I will draw/write up a draft no how to compile the source for the release. There are a few bits that needs to be tied down for release, but i do believe the release is close to being finnished

**Comment by Apprisco** [comment]
Read up on the PR and not sure how it handles multiple identical GPUs. luckily, my GPUs suport WDDM/TCC mode so I just set only the main one to be WDDM, and that works for sunshine.

**Comment by zjoasan** [comment]
@Apprisco to my knowledge, multiple same GPU isn't handled with this coming release. Which is meant as a "intermediate release" of the driver, in order that user can start select GPU. There are stuff in the pipeline, which I can't say which will come true and which will not. But next release will at least be able to tie one GPU to VDD. I've heard users had multiple VDD's installed, so logically you could set different GPU per VDD instance(not per display in one instance). That is what I would try with next release.

Take this for what it is, a suggestion to try. I don't have hardware to test with multiple GPU's and I know there were "strange things" reported by users with multiple VDD's installed.

**Comment by itsmikethetech** [comment]
HDR release with GPU switching is ready for testing in the beta release. https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/24.7.18HDR
