### ISSUE TITLE
"No Man's Sky" cannot detect HDR mode.

### ISSUE THREAD

**Issue by dabinn** [itsmikethetech/Virtual-Display-Driver#124]
I tested several HDR games, and most of them had no issues. However, "No Man's Sky" couldn't detect HDR. This game normally has an HDR option when using a true HDR screen, but it doesn't show up when using VDD.

**Comment by mltheuser** [comment]
I have also encountered this in a few games like "Elden Ring" or "Doom Eternal". When I try to enable HDR in the Video Settings I get a message along the lines of: "The Monitor does not support HDR.".  HDR is definitely on and it also work for some other games like "Monster Hunter World". I also tried to disconnect/disable all other monitors but the issue persists.

**Comment by nlundquist-lilly** [comment]
same issue. seems to occur with many games. this has compelled me to buy an HDMI dummy plug instead of continuing to hassle with virtual displays.

**Comment by nlundquist** [comment]
same issue. this seems to occur in many games. this shortcoming spurred me to buy an hdmi dummy plug. can't continue waiting for virtual display implementations to figure all the bugs out.

**Comment by nlundquist** [comment]
I've summed up that this is due to these games using "NVIDIA-specific NVAPI HDR", which doesn't work the same as the rest of Windows HDR. This is the same reason why these games don't look correct when streaming via Sunshine. 

In Elden Ring SpecialK can rewrite these NVAPI calls on the fly into DXGI which makes the HDR look as expected via Sunshine. This works when using a suitably capable EDID emulator, but I don't believe this approach will work for a VDD (at least not without substantial effort). The NVAPI HDR cannot be enabled without the target display being connected to a Nvidia display adapter.

**Comment by dmitrii-esin** [comment]
I've just played with the Nvidia settings, and it's working fine in all games.

**Comment by BradSimard** [comment]
> I've just played with the Nvidia settings, and it's working fine in all games.

What did you do in particular?

**Comment by dmitrii-esin** [comment]
> > I've just played with the Nvidia settings, and it's working fine in all games.
> 
> What did you do in particular?

I've opened NVidia app and configured advanced hdr settings

**Comment by BradSimard** [comment]
> > > I've just played with the Nvidia settings, and it's working fine in all games.
> > 
> > 
> > What did you do in particular?
> 
> I've opened NVidia app and configured advanced hdr settings

Where?

![Image](https://github.com/user-attachments/assets/2301710a-461f-4d5b-b3d5-6e9c73046072)

The virtual display device doesn't even show up for my 4080 super.

**Comment by dmitrii-esin** [comment]
> > > > I've just played with the Nvidia settings, and it's working fine in all games.
> > > 
> > > 
> > > What did you do in particular?
> > 
> > 
> > I've opened NVidia app and configured advanced hdr settings
> 
> Where?
> 
> ![Image](https://github.com/user-attachments/assets/2301710a-461f-4d5b-b3d5-6e9c73046072)
> 
> The virtual display device doesn't even show up for my 4080 super.

It's a lot of GPU/HDR-related shit here, just play with this stuff (reset to defaults, HDR on/off, Performance tab (restore, autotuning)

![Image](https://github.com/user-attachments/assets/dbf437dd-5079-4292-aff8-668f2419dcf3)
