### ISSUE TITLE
Code 31 on HDR driver

### ISSUE THREAD

**Issue by Rafalskyy** [itsmikethetech/Virtual-Display-Driver#125]
I have a problem with the HDR driver. I keep getting code 31. the version without HDR works fine. Windows version 11 23H2. The beta version causes a black screen and I am forced to restore the system. Option.txt is in C:/IddSampleDriver. I wonder if this is a problem with the IddCx version. Is it possible to check this? I suspect I should have version 1.10 but don't know how to check.

**Comment by itsmikethetech** [comment]
Could be an IddCx version issue. Can you try 23H3?

**Comment by Rafalskyy** [comment]
Thank you for answer! Currently I'm on the Beta branch and there's no any new update. How can I update to 23H3?

**Comment by Rafalskyy** [comment]
Im looking on [iddcx versions](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-versions) and I should have 1.10, but there's two 1.10 versions, one is on 23h2 and second is on windows 2024 platform (?) whatever is it :D

**Comment by Rafalskyy** [comment]
I suppose that clean install of 23H2 will resolve problem (I try to do a repair with a ISO but no luck), but I can't do it and searching for another solution...

**Comment by Rafalskyy** [comment]
Update do 24H2 resolve the problem.
