### ISSUE TITLE
VDD installed, but no HDR selection in Windows 11

### ISSUE THREAD

**Issue by CosmicJ0** [itsmikethetech/Virtual-Display-Driver#127]
VDD Beta Version: 24.7.18
My Windows Version: Windows 11 Home, 23H2, 22631.3880

Using the Windows 11 w/ HDR stable build gave me the Code 31 error, similar to these other issues (#10 & #125), but using beta version 24.7.18 worked. However, I am not seeing HDR as a selectable option for the new virtual display. This may be a dumb question to ask, but would I need any of my actual monitors to have HDR in order for the virtual display to have the option of HDR?

![image](https://github.com/user-attachments/assets/32778c8c-c49c-4872-866b-54f0e28ec0de)

**Comment by bluewolhf** [comment]
I am having the same issue. Also, I did connect an HDR display to my GPU and it did not help.

**Comment by aschulenberg** [comment]
I am also having the same issue

**Comment by aftrmth728** [comment]
Me too, stable didn't work due to code 31 but beta works minus HDR. I have HDR enabled on my other monitor but no option for HDR on the virtual display.

**Comment by matheusfaustino** [comment]
For me, I was able to toggle HDR using the Beta build. I uninstalled the stable on and then the beta and it worked.

**Comment by aftrmth728** [comment]
> For me, I was able to toggle HDR using the Beta build. I uninstalled the stable on and then the beta and it worked.

Did you do anything differently? I can't get HDR through the beta build and can't install stable at all weirdly. Did stable work for you?

**Comment by Rafalskyy** [comment]
Update to 24H2 resolve my problem, you need to change to release preview insider program

**Comment by CosmicJ0** [comment]
> Update to 24H2 resolve my problem, you need to change to release preview insider program

Just updated and now I have the option to turn on HDR on the current VDD beta. Thanks!

![Screenshot 2024-08-24 083023](https://github.com/user-attachments/assets/35cc4d0a-ca4e-4488-9fff-7f325d2adc1f)
