### ISSUE TITLE
Won't install in device manager. Running Windows 11 on arm64 in a VM though...

### ISSUE THREAD

**Issue by krusaderjake** [itsmikethetech/Virtual-Display-Driver#130]
I am on a MacBook Pro with an M3 max chip running windows 11 arm64 in a VMware Fusion VM. I'm trying to test this out to see if it helps with gaming being a recognized display adapter for gaming :) ... I know it's a long shot but ran across this in my searching to get games working running steam in this VM.

My Issue: I run through all the steps successfully except the very end where the device should be added as a display adapter but it just isn't. I go through the addition of legacy hardware manually, click on "have disk", select C:\IddSampleDriver, select the .inf file then nothing happens other than the window goes away for selecting the disk then shows again in less than a second.

**Comment by zjoasan** [comment]
I'm guessing you are using the arm64 variant of windows 11 in that wm? I'm lost in this wm stuff compared to hardware it's running on etc etc. But if that's true you need a version compiled for arm64, as far as i know non of the dev-team have access to hardware to even test such compile. And there are issues with "idd" and arm64 due to version support of underlying library's. So it would be lacking some of the advanced features, like swapchains etc

**Comment by krusaderjake** [comment]
Yea it is windows 11 arm64.

In summary:
macOS Sonoma 14.5 is the real computer I'm on which is based on arm64
VMWare Fusion 13.5 is the VM technology
Windows 11 arm64 is running inside the Virtual Machine

So yea it's a lot going on haha. I figured THAT was why it wasn't working for me so no worries. Just wanted to ask about it to be sure. If you need a tester for arm64, let me know. We can close this issue as it's not really an issue because arm64 and windows is kind of iffy.

**Comment by zjoasan** [comment]
Just did a trial build, and as expected iddcx/umdf version seems to be outdated, 87 errors.

**Comment by itsmikethetech** [comment]
I don't believe the driver is built against any ARM frameworks. I will look into this for future builds.

**Comment by bud3699** [comment]
iddcx is missing some components in arm builds, While theoretically its possible, but we may need a separate driver to do this. I'll start working on a prototype driver tonight

**Comment by itsmikethetech** [comment]
Just updating here to remind that Bud3699 has implemented an ARM64 build. :)
