### ISSUE TITLE
v.23.10.20.2 installed but didn't show Displays (Windows10) v23.10.20.1 worked fine

### ISSUE THREAD

**Issue by baroquedub** [itsmikethetech/Virtual-Display-Driver#132]
Using v.23.10.20.2 I copied the files to C:/ as instructed and ran installCert.bat That installed the driver in one go, no need to go to 'Actions' in Device Manager, however I did have to right click on 'Virtual Desktop Monitor' under display adapters and 'Enable' it. That automatically restarted my PC but after that I could see the display adapter as enabled, however but I couldn't see any additional displays in my settings.

I uninstalled and tried v.23.10.20.1 Thjat installed just as shown in the instructions video (Had to go to Actions and manually point to the driver to make the display adapter appear in Device Manager). That works fine, new display appears in System.

on Windows 10.

**Comment by itsmikethetech** [comment]
You need to go to actions to properly add it. This is why it didn't show up properly. The cert only installs the cert. Not the driver.

**Comment by baroquedub** [comment]
That's what's odd, there were no Action options when I installed v.23.10.20.2. The display adapter showed up (disabled) and opening Actions was empty apart from 'Help'

**Comment by itsmikethetech** [comment]
It only shows up when you select Display Adapters. Because it's a sub action of that category.

**Comment by baroquedub** [comment]
Ah. gotcha. user error :)

**Comment by itsmikethetech** [comment]
No worries! Did it work after trying that?

**Comment by baroquedub** [comment]
Well I got the virtual display appearing in my display settings on v.23.10.20.1 so I stayed with that, but... For some reason it wouldn't stream from Sunshine to Moonlight on my VisionPro (which is what I wanted it for). But not sure if that's to do with your driver so didn't want to trouble you about it. Also it would be another ticket :)

**Comment by itsmikethetech** [comment]
Ah, ok. Sounds good! I've got a video that shows how to configure Sunshine and specify the display as well if that helps. Feel free to submit a ticket and we can try to help. :)
