### ISSUE TITLE
How to use multiple virtual display driver

### ISSUE THREAD

**Issue by Mystraht** [itsmikethetech/Virtual-Display-Driver#135]
Hello,

First of all, your virtual display driver works like a charm! Thanks for all your hard work.
I want to emulate two virtual screens. How can I achieve that, please? I guess I should use two different certificates, right?
Could you please provide me with the steps to do that?

Thanks in advance.

**Comment by bud3699** [comment]
If you're using old stable release that edit the top line of option.txt file. However if you're using the new release. The xml takes priority. Open that file. A display count should be there, modify that to how many displays you want

**Comment by Mystraht** [comment]
That work well, thanks!

**Comment by bud3699** [comment]
No problemo. I'll close this issue then. If there is any further problems or things you need help with, then feel free to ask the question in the discord or pop open another issue! 

Have a wonderful day!
