### ISSUE TITLE
windows10  installation was successful. But the monitor list cannot be seen.

### ISSUE THREAD

**Issue by kuangke9527** [itsmikethetech/Virtual-Display-Driver#145]
![屏幕截图_20240829_100608](https://github.com/user-attachments/assets/5a0e8189-7811-4ffd-be39-ffda3b965826)
Detailed information in the picture

**Comment by kuangke9527** [comment]
@itsmikethetech please help me.

**Comment by zjoasan** [comment]
Which sub/release version of Windows 10 are you using?

**Comment by kuangke9527** [comment]
version is 10.18363.592.1

**Comment by kuangke9527** [comment]
> Which sub/release version of Windows 10 are you using?

10.18363.592.1

**Comment by zjoasan** [comment]
With a bit of research, to be able to enjoy this driver you have to use 10 build 1904* or later. This is the lowest that would work, I believe from reading official MS documents about the feature.:

Windows10 19041, also know as 20H1/Vb . Released May 2020. The version of the system software, which VDD is based on, isn't compatible with binding GPU and a whole set of other functions.

So if you aim to use this software, suggest you update OS to the most recent build.

Good Luck

**Comment by kuangke9527** [comment]
thanks!

**Comment by Wundrwaffle** [comment]
Same.
Win10Pro
OS: 22H2 ver /  19045.4780 build

**Comment by bud3699** [comment]
anyone with issues, please may you try the beta enabling logs within the vdd_settings.xml then create an issue request and upload your logs so we can diagnose the issue

**Comment by Wundrwaffle** [comment]
> anyone with issues, please may you try the beta enabling logs within the vdd_settings.xml then create an issue request and upload your logs so we can diagnose the issue

Can you explain please the way to do this? Where should i look at to enable it?

**Comment by Wundrwaffle** [comment]
> beta enabling logs within the vdd_settings.xml

Ok... Seems i found the issue. In the youtube tutorial, author shows link from main repository page. But there are version for win11. I took this one: Virtual Display Driver 23.10.20.2 (Windows 10+) NonHDR version, and now i have 2 monitors.

![2024-10-09_10-30-49](https://github.com/user-attachments/assets/a82f4069-8db0-45d9-a5b3-f91c938829e9)

**Comment by bud3699** [comment]
Ah, installing wrong version then

**Comment by Wundrwaffle** [comment]
> Ah, installing wrong version then

And you can see that previous users also installed HDR version, that seems was taken from main page. But for different OS version. You can put kind of RED sign at main to be careful when downloading archive )))

Thank you, anyway, now its time to test it )))

**Comment by bud3699** [comment]
If you look at the commit history that was me an hour ago adding the important notice, the links have always been here. We appreciate your consideration on release but as of now upholding two different drivers have been deprecated in favour for our beta release with single driver support. For the mistake of downloading the incorrect by clicking latest release, that is user error, if the user decides not to read the GitHub readme first then that's user error. The website itself may be easier for you to read downloads

**Comment by bud3699** [comment]
> Indded a user error. Also I am not a developer so sorry no idea on how release version control and other stuff in github works, so sorry on that part as well as part for not reading readme. I did not start at github I started at the video tutorial on youtube and jumped on to github with straight up to releases ( muscle memory for obtaining latest stuff ) so that way my bad in my use case to not read the instructions. Just posted images if someone looks back at their mistake same as mine to refer what went wrong. Hope it help. Hoping that single driver support soon comes out of beta, good luck. Have a good one ahead. 😊 



Yes, no problemo! I updated the readme and adjusted the install instructions to hopefully steer away from any confusion in future! Thanks for the feedback! And hopefully getting the beta out to release soon too!

**Comment by bud3699** [comment]
@kuangke9527 did you resolve this issue too? Was it downloading incorrect version. If so I'll mark the issue as completed and close it

**Comment by kuangke9527** [comment]
> @kuangke9527 did you resolve this issue too? Was it downloading incorrect version. If so I'll mark the issue as completed and close it

sorry. I tried something else. I'm not sure if I downloaded the wrong version. You can turn it off. Thanks.

**Comment by yinkaisheng** [comment]
VDD.23.10.20.3.zip works for Windows 10 22H2.
