### ISSUE TITLE
Uninstalling and reinstalling the driver causing multiple monitors being added

### ISSUE THREAD

**Issue by KrisCris** [itsmikethetech/Virtual-Display-Driver#146]
After the first uninstall, and reinstall, I found there are two virtual displays created... And I am unable to remove the driver.
```powershell
pnputil /delete-driver oem90.inf
Microsoft PnP Utility

Failed to delete driver package: One or more devices are presently installed using the specified INF.
```

To remove all these displays, I have to force uninstall the driver via:
```powershell
pnputil /delete-driver oem90.inf /force /uninstall
```
and it worked.

However, any reinstall adds one more display to my system... and this is the third reinstall

![image](https://github.com/user-attachments/assets/13bcf1dd-e818-4253-9665-c873a2dfa79d)
![image](https://github.com/user-attachments/assets/60f48627-50da-44f9-92e8-0b93112b96d3)

**Comment by KrisCris** [comment]
Nvm, by uninstalling the duplicated Display Adapters fixed the issue.

**Comment by HornetXR5** [comment]
Hi, just wondering if i can reopen this as I have the same issue but uninstalling the duplicates does not solve anything. On reboot they all reappear

**Comment by HornetXR5** [comment]
Follow up post for anyone else that gets the issue and uninstalling doesn't fix it - Uninstall the display from device manager whilst in safe mode
