### ISSUE TITLE
Is it possible to create a virtual touch screen?

### ISSUE THREAD

**Issue by BadSephiroth** [itsmikethetech/Virtual-Display-Driver#150]
As the title say, I would like to create a virtual touch screen instead of a regular virtual display. Does this tool allow that?
Thank you.

**Comment by zjoasan** [comment]
What do you mean with a **_virtual_** device that needs **_physical_** input?? The question doesn't make sense to me. But English isn't my native tongue.

Would please, elaborate on this?

**Comment by bud3699** [comment]
> What do you mean with a **_virtual_** device that needs **_physical_** input?? The question doesn't make sense to me. But English isn't my native tongue.
> 
> 
> 
> Would please, elaborate on this?

I believe he means he will be connecting to a virtual display from a touch screen device therefore wants the display to accept touch screen input. I could be wrong

**Comment by BadSephiroth** [comment]
> > What do you mean with a **_virtual_** device that needs **_physical_** input?? The question doesn't make sense to me. But English isn't my native tongue.
> > Would please, elaborate on this?
> 
> I believe he means he will be connecting to a virtual display from a touch screen device therefore wants the display to accept touch screen input. I could be wrong

Yes, this was the idea but I've discovered that a fork of Moonlight for Android enable this function client side on my tablet, so now the "regular" virtual display will be read as a Windows multi-touch input, solving my issue.

By the way those are the two Moonlight forks that enable this function, if anyone like me is interested in it:
https://github.com/MuhamadRifkii/moonlight-android
https://github.com/TrueZhuangJia/moonlight-android-Enhanced-MultiTouch

**Comment by flejz** [comment]
I am also interested in this feature. Allow me to explain why:

If I have a Windows device that has touch capabilities and lacks a keyboard (a Windows tablet, for instance), I will be able to input text by using Windows Touch Keyboard as soon as a text field input gain focus. It comes up automatically in case it detects the display supports touch input.

If however another monitor gets detected and such does not have touch capabilities, the Touch Keyboard will stop being displayed automatically on text input focus. That will be the case for a virtual display as well, so having a virtual display with touch capabilities would enable a primarily touch screen Windows device to keep all it's functions when used in conjunction with a virtual display.
