### ISSUE TITLE
which release tag is for hdr and non-hdr?

### ISSUE THREAD

**Issue by comsyspro** [itsmikethetech/Virtual-Display-Driver#151]
Could you please give an overview which realease tag to use for stable drivers. At the moment it is not clear which one to take and I'm a little confused about the many different release tags and OS versions with and without HDR.

1. non HDR Windows 10 -> which release tag?
2. non HDR Windows 11 -> which release tag?
3. HDR Windows 11 -> which release tag?

And is HDR also possible for Windows 10?

Thank you.

**Comment by bud3699** [comment]
Windows 10 doesn't support HDR

The latest stable release is windows 11 only, this supports HDR, two releases before that is the stable release for windows 10 (this says windows 10) and this does not support HDR


The pre-release drivers contain both windows 11 and 10 support but support for windows 10 is limited to later versions of windows 10 and windows 10 does not support HDR

**Comment by comsyspro** [comment]
Thank you. For better understanding it would be good to have a table with a matrix containing the release tag number, OS support for Win 10 / Win 11, and if HDR support yes/no and probably a feature field. Could you please do this to help with getting the correct information. At the moment you can do some mistakes for example there is s tag 23.12.2HDR which do not have HDR support and this is somehow difficult to find out without such a table matrix.

**Comment by bud3699** [comment]
> Thank you. For better understanding it would be good to have a table with a matrix containing the release tag number, OS support for Win 10 / Win 11, and if HDR support yes/no and probably a feature field. Could you please do this to help with getting the correct information. At the moment you can do some mistakes for example there is s tag 23.12.2HDR which do not have HDR support and this is somehow difficult to find out without such a table matrix.

We do reference the versions inside the readme on the main page. Specifying what version of the driver to get based of operating system

**Comment by comsyspro** [comment]
Yes, but there I think are some infos which can lead to misunderstandings. On the latest release https://github.com/itsmikethetech/Virtual-Display-Driver there is this info here https://github.com/itsmikethetech/Virtual-Display-Driver?tab=readme-ov-file#download-stable-version that [Windows 11 23H2+ (HDR)](https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/23.12.2HDR) do support HDR. But when you go to the source code of 23.12.2HDR https://github.com/itsmikethetech/Virtual-Display-Driver/tree/23.12.2HDR?tab=readme-ov-file than this code doesn't have HDR functions included. So because of that it is confusing and I asked for a simple table matrix with correct infos.

**Comment by itsmikethetech** [comment]
- Windows 10/11 Non-HDR (23.10.20.2)
- Windows 11 Only HDR (23.12.2)
- Universal Driver (24.9.11, still requires Win11 for HDR)
