### ISSUE TITLE
Beta 24.8.6 XML file transposed digits

### ISSUE THREAD

**Issue by Vexz00** [itsmikethetech/Virtual-Display-Driver#153]
Just wanna point you to an issue that made my hair go grey until I realized it.

In the Beta version 24.8.6 you added the XML configuration (`vdd_settings.xml`). In the last group in that XML file for 4K resolution you set `3480` pixels for width. The actual width for 4K resolution (16:9 format) is `3840` pixels.

```
        <resolution>
            <width>3480</width> <!-- CHANGE THIS TO 3840 -->
            <height>2160</height>
            <refresh_rate>30</refresh_rate>
            <refresh_rate>60</refresh_rate>
            <refresh_rate>90</refresh_rate>
            <refresh_rate>120</refresh_rate>
            <refresh_rate>144</refresh_rate>
            <refresh_rate>165</refresh_rate>
        </resolution>
```

**Comment by bud3699** [comment]
Yes, we are aware, its been mentioned a dozen, thanks anyway though

**Comment by Vexz00** [comment]
Ah okay, sorry about that. I probably was too blind to find an open issue mentioning this problem.

**Comment by bud3699** [comment]
All good, you didn't know, hope you enjoy the driver though, It will be fixed in the next beta release, which should hopefully be coming soon, Am I oki to close this issue now ?

**Comment by Vexz00** [comment]
I'm gonna close it for you. Thank you!
