### ISSUE TITLE
Support for changing bit depth 

### ISSUE THREAD

**Issue by tb115** [itsmikethetech/Virtual-Display-Driver#158]
Hi there,

I stream to my laptop which only supports 6bit color.
When using the default 8 bit depth colours look muted.
When in game this is less noticable but using the desktop is not a very good look.

I understand that higher color depths 10bit and 12 bit are in the works but was wondering if this can be customized in the future.

Thank you for your work!

**Comment by itsmikethetech** [comment]
Latest commit from @bud3699 includes this. 👍 Souce available now, release coming shortly.

**Comment by xDoge26** [comment]
can we create virtual display with less than 8 bit depth?
