### ISSUE TITLE
How can I load a EDID and emulate a specific display?

### ISSUE THREAD

**Issue by advanced03** [itsmikethetech/Virtual-Display-Driver#160]
I need to emulate a specific display, but if I use CRU to load the EDID nothing really happens, is there any way?

**Comment by bud3699** [comment]
You could place your edid in the placeholder edid for now then rebuild the code?

**Comment by advanced03** [comment]
> You could place your edid in the placeholder edid for now then rebuild the code?

Is there a guide on how to rebuild the program?

**Comment by zjoasan** [comment]
Just  a heads-up, the driver don't parse most of the data stored in a EDID file, there are some work to remedy the situation, but due to time restrictions it's a slow progress. I'll gladly give current work to a c++ fluent windows developer. I don't have enough previous  experience or knowledge to handle integration of what is needed, and filter out what isn't needed / working.

**Comment by zjoasan** [comment]
Just a question, which parts of the EDID is it that you are looking to setup in VDD? I'm still working on this, slowly...

**Comment by zjoasan** [comment]
@advanced03 Which are the main characteristics you want from your EDID? 

If you need to know what I mean, then I suggest you browse wiki article for EDID: 
https://en.wikipedia.org/wiki/Extended_Display_Identification_Data 
and get back to me, so I can focus my efforts at that first while building the parser.

**Comment by advanced03** [comment]
As much as possible, I'm looking to emulate a laptop display to hopefully get GSYNC working again.

**Comment by zjoasan** [comment]
Well, EDID holds a lot of data, is it resolutions, hdr data, color management that you feel is most urgent?

I need more specific "goals" to aim at, since I have to integrate it bit by bit. So I would like a "wish-list" of priorities, if you get what I mean.

**Comment by advanced03** [comment]
@zjoasan 

It doesn't really matter to me since I need all of it anyways. 

Whatever is the most convenient to you :)

**Comment by zjoasan** [comment]
Well If you try the new beta, with user-edid.bin. See if that gives you the result you want. This is an intermidiate soution for EDID, since it won't effect resolutions, but will grabb HDR-meta data and suff.

**Comment by advanced03** [comment]
Thank you very much for even considering my kinda vague request, I will try this and let you know how it goes.

**Comment by advanced03** [comment]
Thanks for your instructions, I've managed to make it work although I had to change the name from generic display to the correct one.

Unfortunately the screen doesn't get recognized by nvidia control panel, so I wasn't able to do what I hoped but it's still cool.

Is it technically possible for the virtual display to get recognized by Nvidia control panel?

**Comment by bud3699** [comment]
As of right now, that is a no go, Sorry about that. I'm not saying not possible at all, but if it is, I'm not aware and probably wont be easy

**Comment by advanced03** [comment]
> As of right now, that is a no go, Sorry about that. I'm not saying not possible at all, but if it is, I'm not aware and probably wont be easy


Totally undrrstandable! I know my request is a bit unreasonable (basically perfect emulation of a screen as if it was physically connected).

I guess this kind of thing is only possible with a reprogrammable dummy plug (usb c in my case because I need displayport) but I don't think such thing exists.
