### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Valac-Design** [itsmikethetech/Virtual-Display-Driver#168]
I saw comments that ipad resolution was supported but both stable releases, as well the beta, only show me standard resolutions of 480p, 720p, 1080p, 4k. 

I see some comments also about needing to rebuild some sort of XML file to get the result and it still not working for people, I thought when the developer said "added support for it" that it meant an easy resolution change was possible in displays?? I'm beyond confused

**Comment by Valac-Design** [comment]
I see some comments also about needing to rebuild some sort of XML file to get the result and it still not working for people, I thought when the developer said "added support for it" that it meant an easy resolution change was possible in displays?? I'm beyond confused

**Comment by bud3699** [comment]
If you followed the instructions then you should have copied in a file called vdd_settings.xml

Editing this adding custom resolutions in the same format provided

**Comment by Valac-Design** [comment]
Aight, didn't really "add support" if I gotta fill out the file myself though, can't wait for the installer to actually address this the way he made it sound. Considering forking it myself.

**Comment by bud3699** [comment]
> Aight, didn't really "add support" if I gotta fill out the file myself though, can't wait for the installer to actually address this the way he made it sound. Considering forking it myself.
> 
> 
> 
> edit: Didn't work, same as many others have noted.
> 
> 
> 
> edit2: man I give up, this is completely out of my element, I appreciate the normal resolutions but when you say you added support, they should be in the main file.



We have a fall back with presets but the support is still added, just because it may not be easily accessible the support was still added, allowing people to use these custom resolutions and create applications to do so. So yes we did "add support" in your words, sorry we can't please everyone's needs but the resources are there!

**Comment by Valac-Design** [comment]
Well despite my efforts it did not work for me, maybe if you add the custom ones prior to the first install, or go attempt to remove and re-add it may, but it seems the pre-xml version was a simple options.txt that worked. Best of luck on the transition to XML and an eventual GUI.

**Comment by aidin-foroughi** [comment]
I attempted to remove and re-add, and the custom added resolutions still don't show up.

**Comment by bud3699** [comment]
Its using the fall back most likely
Make sure the folder names are correct 

Release: C:/IddSampleDriver
Beta: C:/VirtualDisplayDriver

**Comment by RuneInfantry** [comment]
@Valac-Design @aidin-foroughi , after uninstalling the device and driver in Device Manager, it took a full restart of my computer before the resolutions showed up in my windows display settings.

If that still doesn't work for you, using the non-beta version of the driver definitely works for this use case as well.

**Comment by bud3699** [comment]
or disable and re-enable the driver

**Comment by Valac-Design** [comment]
Here's what I did to get it working. 
- Right click taskbar -> Device Manager -> Remove the Virtual Display Driver and Virtual Display Monitor (Might also say HDR).
- Reinstall latest version with the auto installer
- Navigate to the beta folder (Seen above, despite being a stable release) C:/VirtualDisplayDriver
- Open "vdd_settings.xml" in Notepad or similar software
- Add:
- `        <resolution>
            <width>2420</width>
            <height>1668</height>
            <refresh_rate>30</refresh_rate>
        </resolution>`
* Keep refresh at 30, you can still change it with the display settings later
- Right click the tray icon on the newest ver, click reload settings, then reload driver.
- Reboot
