### ISSUE TITLE
Moonlight - Failed to initialize video capture

### ISSUE THREAD

**Issue by ToxicOtaku** [itsmikethetech/Virtual-Display-Driver#171]
I've installed the beta version, added my specific display res of 3120x1440, 120Hz as I am streaming to my phone. I've got the virtual display showing in display list and set to the resolution/RR that I want, HDR off. I've set Sunshine to \\.\DISPLAY4 and applied the change. When I try to connect via Moonlight it fails. If i leave it to default it selects the primary monitor plugged into my 3070. Not sure if my CPU not having an iGPU is the reason for this, or if I can set the VDD to run off the GPU. Also ot sure where the proper place to submit my query is so apologies if this is not it.

**Comment by bud3699** [comment]
1) The driver will automatically pick the gpu with highest vram in the beta driver, you can change this in the xml by adding your gpu friendly name

2) I believe there is an issue when streaming if its not your main display, You could try setting the virtual display to be the main display

**Comment by ToxicOtaku** [comment]
I had guessed since i have 3 monitors that \\.\DISPLAY4 would be what to use. After reviewing and checking the dxgi-info.exe i can see i was using the wrong one. Sorry and thank you for the input!

**Comment by bud3699** [comment]
No problemo! Is it working then ?

**Comment by ToxicOtaku** [comment]
Aye sir! Absolutely perfectly and beautifully. 🤜🤛
