### ISSUE TITLE
[Bug]: Driver without digital signature

### ISSUE THREAD

**Issue by Danzikks** [itsmikethetech/Virtual-Display-Driver#174]
### Which OS?

Win11 Pro

### Which release?

23H2

### Describe the bug

Hi I can't install the driver, Windows swears that the driver is not digitally signed.
The funny thing is that yesterday and the day before yesterday it was fine, but today it stopped, nothing has changed. I'm just looking for a better resolution to scale my MacBook. And now I can't install the driver at all.
![CleanShot 2024-10-15 at 00 25 09@2x](https://github.com/user-attachments/assets/16c7105e-a670-481d-92eb-4e414926cc24)

**Comment by itsmikethetech** [comment]
The old certificate expired. Please re-download the release and reinstall with the newest certificate. The new one should be good for 10 years. 👍 Let us know if it worked and we can update the ticket.

**Comment by Danzikks** [comment]
> The old certificate expired. Please re-download the release and reinstall with the newest certificate. The new one should be good for 10 years. 👍 Let us know if it worked and we can update the ticket.

Все работает, спасибо. Странно, что я проверил, прежде чем написать этот вопрос, загрузил сертификат снова, и он не работал, но в тот момент я не переустанавливал сертификат, не очищал его в certmgr.msc. Сейчас почистил старые сертификаты и заработало🤝

**Comment by fr1g** [comment]
me also and tried over and over again until i found that i downloaded an older driver of beta version XD
