### ISSUE TITLE
[Bug]: The ALPC message requested is no longer available. Code 31

### ISSUE THREAD

**Issue by AsrielDewitt** [itsmikethetech/Virtual-Display-Driver#175]
### Which OS?

Win11 Pro

### Which release?

23H2

### Describe the bug

![image](https://github.com/user-attachments/assets/7cafd3e8-1171-4fd1-a00c-3125e7c8cd42)

### Steps to reproduce

Same way to install it. Nothing change

### Expected behavior

Have a secondary virtual display, which there is non

**Comment by AsrielDewitt** [comment]
Nevermind, wrong folder for option.txt

**Comment by bud3699** [comment]
Yeh, the beta build will have no problem running without the folder. Nevertheless glad you got it sorted!

**Comment by MustafaHilmiYAVUZHAN** [comment]
bro I have same problem. how to solve this problem.I didn't understand this

**Comment by MustafaHilmiYAVUZHAN** [comment]
@AsrielDewitt

**Comment by bud3699** [comment]
either use beta for configless or make sure the folders are in the correct locaiton

**Comment by MustafaHilmiYAVUZHAN** [comment]
Beta didn't work but it worked when I put it in the correct Location, C directory

**Comment by bud3699** [comment]
beta should work regardless of location due to it having a fall back, are you 100% sure you used the beta?

**Comment by MustafaHilmiYAVUZHAN** [comment]
Yes, but I changed the folder name. That's probably why or maybe I didn't do something.

**Comment by MustafaHilmiYAVUZHAN** [comment]
Yes, but I changed the folder name. That's probably why or maybe I didn't do something.
