### ISSUE TITLE
[Feature]: 72hz Refresh rate 

### ISSUE THREAD

**Issue by pitluko** [itsmikethetech/Virtual-Display-Driver#185]
### Is the feature related to a "problem"?

Can you please add a 72Hz refresh rate to match my VR headset?
The Nvidia refresh rate setting "FAST" makes the image projection smoother in some games with the 90Hz setting, but maintaining 90 FPS in VR is very difficult. My Pico 4 does not support 60Hz, so the next lower step would be 72Hz, which is not supported by your driver.

Other than that, great work!

### Your suggestion

Add 72hz to refresh rate

**Comment by bud3699** [comment]
You can change it in either the xml or the option.txt depending on what version you're using

**Comment by pitluko** [comment]
I'm using the newest beta.

**Comment by pitluko** [comment]
THX! i found it! This went FAST!

**Comment by bud3699** [comment]
yeh, just pop it open, look for the resolution you want to add 72hz too and add a refresh rate. Or you can use the xml editor on the website

https://vdd.mikethetech.com/#xmlConfig

**Comment by bud3699** [comment]
> THX! i found it! This went FAST!

I had just turned my computer on and opened discord the second you opened the issue
