### ISSUE TITLE
[Bug]: Hyper-v GPU-P only shows high refresh rates on 1920x1080

### ISSUE THREAD

**Issue by oKFCo** [itsmikethetech/Virtual-Display-Driver#193]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

Using GPU-P + parsec on Hyper-V Win 11 pro guest doesn't show high refresh rate options for any other resolution than 1920x1080

![Screenshot 2024-11-23 174358](https://github.com/user-attachments/assets/ab84bdeb-9d8c-4ed4-b797-0d05c22357da)
![Screenshot 2024-11-23 174354](https://github.com/user-attachments/assets/c5f94605-f957-4e6b-8bc8-d0044f6245a9)
![Screenshot 2024-11-23 174347](https://github.com/user-attachments/assets/f62a8fc0-8ac4-4933-bcbc-0568f13826d5)

RTX 4090
LG C1 (TV)

relevant links:
https://forum.level1techs.com/t/2-gamers-1-gpu-with-hyper-v-gpu-p-gpu-partitioning-finally-made-possible-with-hyperv/172234

**Comment by bud3699** [comment]
and did you add the custom refresh rates to option.txt or vdd_settings.xml (if using beta)

**Comment by oKFCo** [comment]
> and did you add the custom refresh rates to option.txt or vdd_settings.xml (if using beta)
That did indeed work! Perhaps you could include that in the README.

**Comment by oKFCo** [comment]
> and did you add the custom refresh rates to option.txt or vdd_settings.xml (if using beta)

That did indeed work! Perhaps you could include that in the README.
