### ISSUE TITLE
[Bug]: Not compatible with Windows Server 2022

### ISSUE THREAD

**Issue by mohamedabdelaalkhalifa** [itsmikethetech/Virtual-Display-Driver#199]
### Which OS?

Other..

### Which release?

21H2

### Describe the bug

Device Manager showing the below error:
This device is not working properly because Windows cannot load the drivers required for this device. (Code 31)
The ALPC message requested is no longer available.

![image](https://github.com/user-attachments/assets/8e1fca67-bf4b-4376-abbd-c24e5d3d2729)

![image](https://github.com/user-attachments/assets/b3d75fb5-30a6-4dcf-9b18-128ad7d66e3e)

### Contact Details

mohamed.abdelaal.khalifa@gmail.com

**Comment by bud3699** [comment]
did you try the beta

**Comment by mohamedabdelaalkhalifa** [comment]
I tried the Beta version, and driver is now working but after restart the display resolution revert to the smallest resolution and not the previously selected.

**Comment by bud3699** [comment]
its probably how windows server handles the driver, you can just remove the resolutions from the xml you don't want (the first is the default)

**Comment by mohamedabdelaalkhalifa** [comment]
> its probably how windows server handles the driver, you can just remove the resolutions from the xml you don't want (the first is the default)

Should I have to uninstall the driver and re-install it ? or I have to modify the XML only ?

**Comment by bud3699** [comment]
modify xml, disable and re-enable the driver or restart
