### ISSUE TITLE
New version with HDR created 2 displays and uninstalling them from hardware manager doesn't remove them after reboot

### ISSUE THREAD

**Issue by alwayscur1ous** [itsmikethetech/Virtual-Display-Driver#22]
I just installed the new version with HDR and it created 2 displays. If I uninstall them in hardware manager they still show in display properties and after a reboot they show back up in device manger.

**Comment by alwayscur1ous** [comment]
Figured it out

**Comment by Foul-Tarnished** [comment]
> Figured it out

bruh at least tell how you did it
