### ISSUE TITLE
Only see 60hz as an option

### ISSUE THREAD

**Issue by sittingmongoose** [itsmikethetech/Virtual-Display-Driver#23]
I am using the newest version of Windows 11, using an nvidia 3090 with the newest drivers.  I am only getting the option in windows to set to 60hz though.  Is there a different place to change refresh rate?  This all works outside of that, HDR and different resolutions.

**Comment by blackgold9** [comment]
This was it for me. I added the lines to option.txt then disabled/re-enabled to driver in device manager to see the changes

**Comment by blackgold9** [comment]
Recommend closing this issue.

**Comment by Barina** [comment]
> then disabled/re-enabled to driver in device manager

Do you guys have a better way to "turn" the monitor on\off?
I tried the `devcon.exe` approach but it didn't work.

**Comment by itsmikethetech** [comment]
Merged a PS script that does this: [Script](https://github.com/itsmikethetech/Virtual-Display-Driver/blob/master/scripts/toggle-VDD.ps1)

**Comment by Barina** [comment]
> Merged a PS script that does this: [Script](https://github.com/itsmikethetech/Virtual-Display-Driver/blob/master/scripts/toggle-VDD.ps1)

Awesome! 
It doesn't work for me tho..

```
PS D:\Roy\Downloads> .\toggle-VDD.ps1
Cannot invoke method. Method invocation is supported only on core types in this language mode.
At D:\Roy\Downloads\toggle-VDD.ps1:2 char:6
+  if (-Not ([Security.Principal.WindowsPrincipal] [Security.Principal. ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage

Enabling device
enable-pnpdevice : Generic failure
At D:\Roy\Downloads\toggle-VDD.ps1:16 char:49
+ ... te-Host "Enabling device"; $device | enable-pnpdevice -Confirm:$false
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Win32_PnPEntity...\DISPLAY\0000"):ROOT\cimv2\Win32_PnPEntity) [Enable-PnpDevice],
    CimException
    + FullyQualifiedErrorId : HRESULT 0x80041001,Enable-PnpDevice
```
