### ISSUE TITLE
Duplicate cursor (due to hardware cursor)

### ISSUE THREAD

**Issue by Paarush** [itsmikethetech/Virtual-Display-Driver#25]
A duplicate cursor appears when using this driver and streaming via moonlight/sunshine. The cursor seems to get duplicate when the cursor type changes (for example resizing windows, hovering over buttons or hovering over text). A similar issue was mentioned upstream. I have attached them for your reference.

Photo for reference:

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/63594290/77bf0dc3-2257-4d8d-a401-c25f765060fd)

https://github.com/ge9/IddSampleDriver/issues/15
https://github.com/roshkins/IddSampleDriver/issues/6
https://github.com/microsoft/Windows-driver-samples/issues/531

**Comment by Jshauk** [comment]
I'm having a similar issue except my cursor only shows up on the virtual monitor when streaming from my quest 3 headset in immersed. I'm on Windows 10 22h2 - nvidia 4070 if that matters.

**Comment by jonginator** [comment]
Also looking for a way to eliminate the double cursor issue.

**Comment by TonyShu1218** [comment]
same issue here when streaming using chrome remote desktop. I'm on win11 22h2

**Comment by jonginator** [comment]
Is VDD dead?

I haven't seen a single comment acknowledging the issue.

**Comment by hhmfs** [comment]
经过尝试，我发现，如果在设备管理器中刚安装好虚拟屏幕，则不会出现两个鼠标。如果断开远程连接再连上就会出现两个鼠标。如果此时在设备管理器中禁用虚拟屏幕，再启用，就又是一个鼠标的正确情况

**Comment by bud3699** [comment]
> 经过尝试，我发现，如果在设备管理器中刚安装好虚拟屏幕，则不会出现两个鼠标。如果断开远程连接再连上就会出现两个鼠标。如果此时在设备管理器中禁用虚拟屏幕，再启用，就又是一个鼠标的正确情况


**Translated: **

After trying it, I found that if the virtual screen was just installed in the device manager, the two mice would not appear.  If you disconnect the remote connection and then connect it again, two mice will appear.  If you disable the virtual screen in the device manager at this time and then enable it, it will be a correct mouse situation again.




**Also. As a side note. Please try keep all conversations in English**

**Comment by bud3699** [comment]
> Is VDD dead?
> 
> I haven't seen a single comment acknowledging the issue. 


Mike has been working on development on Rite Of Eris and working on his YouTube channel and his career. So sometimes he can be too busy to sit reading issues. The man  is a legend. 

He answers better in the discord

https://discord.mikethetech.com

**Comment by wesgurn** [comment]
Any update on the fix for the duplicate cursor issue?  If I disable the driver in Device Manager the issue goes away, but then I have to keep the monitor on when I use Sunshine.

I was trying to figure out how to disable the hardware cursor via the API.

**Comment by ping-armo-fati** [comment]
same problem, leave a message here for check after.
if solved,  thank for reminding

**Comment by tuananhwanosoft** [comment]
I got same problem, 
if solved, thank for reminding

**Comment by itsmikethetech** [comment]
Latest source push from @bud3699 fixes this issue. Public release coming soon.
