### ISSUE TITLE
HDR support on Windows 10?

### ISSUE THREAD

**Issue by fidoboy** [itsmikethetech/Virtual-Display-Driver#26]
Why is there a HDR version for Windows 11 but there is not for Windows 10? Are there technical issues? I'll like to try this driver but I can't use Windows 11. Is there any plans to add HDR support for Windows 10?

**Comment by bud3699** [comment]
HDR depends on windows 11. Technically, might be a way. But for now, don't depend on it

**Comment by itsmikethetech** [comment]
Yes, unfortunately Microsoft has no public plans to push the appropriate software update for HDR support on Windows 10. Until they do, we don't have a method to enable it. Will reopen if we figure out another way, or if Microsoft releases an update for Windows 10.
