### ISSUE TITLE
[WIN10_X64] (VDD.23.10.21) Blank Display Screen

### ISSUE THREAD

**Issue by AlexAnimateMp4** [itsmikethetech/Virtual-Display-Driver#44]
Hello.

I did follow the installation tutorial, but unfortunately the virtual display screen is blank (both in the settings and on display).

Note: When I expand the displays, I do get an image, but it's impossible to interact with any application (it shows me the Windows desktop).
I assume that the virtual display screen is displayed as the main screen.

<img width="960" alt="Driver" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/48261899/449572c6-2ddd-45a8-9063-c7fcfdb204f2">
<br>
<img width="175" alt="Devices" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/48261899/b13891f5-4277-4f6d-878f-449f71084aa1">
<br>
<img width="484" alt="Displays" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/48261899/27c60441-2237-4f13-a146-7abbe15394e0">
<br>
<img width="238" alt="Scale" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/48261899/341b32ac-4431-4f00-8332-dc8e5b448499">
<br>
<img width="345" alt="WinVer" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/48261899/fd6fac64-29e2-4b00-9d0c-11dc4f5bc311">

**Comment by bud3699** [comment]
Have you tried removing and reinstalling it ?
