### ISSUE TITLE
Latest Windows 11 not working w/ HDR functionality.

### ISSUE THREAD

**Issue by psiberfunk** [itsmikethetech/Virtual-Display-Driver#47]
I'm pretty certain I installed the latest driver with HDR support (supposedly).. but while windows sees my real monitor with HDR fine, this is what I get with the emulated display.. and i'm totally baffled as to why:

Is this a bug ?  I followed the install instructions to a T.
 
<img width="822" alt="image" src="https://github.com/itsmikethetech/Virtual-Display-Driver/assets/19777571/c90f00d9-e993-4244-b826-86fe4702528f">

**Comment by juniordurant** [comment]
I am having the same issue

**Comment by itsmikethetech** [comment]
Shouldn't show up in Advanced Display, I see it in Display:

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/25166211/2155099c-8fac-483a-ac12-bbd729ab78e2)
