### ISSUE TITLE
Help wanted - Cannot open source file "iddcx.h"

### ISSUE THREAD

**Issue by DandamanAUS** [itsmikethetech/Virtual-Display-Driver#52]
Hi I am using windows and Visual Studio 2022. 
Does this project have any pre-requsistes to build it locally? Did I see something about VS 2017?
I get error:
Cannot open source file "iddcx.h".
Plus many more I can only assume is because of this.
VS handles all the 'making' and compling right?

**Comment by zjoasan** [comment]
Try step 1,2 and 3 that should fix the issue, it did for me.

https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by itsmikethetech** [comment]
I agree with zjoasan's comment, it's usually that it's missing the WDK or SDK.
