### ISSUE TITLE
add support for 1334 x 750 [retroid pocket 3(+) and 4 (pro)]

### ISSUE THREAD

**Issue by peacepenguin** [itsmikethetech/Virtual-Display-Driver#55]
The retroid pocket handheld devices use an odd screen resolution: 1334 x 750

Can you add both a landscape and portrait version of this resolution? This will help moonlight streaming to this device look nice and crisp. Thanks for the awesome driver!

1334 x 750

750 x 1334

**Comment by FangLecheng** [comment]
你可以自己手动添加自定义的分辨率

**Comment by peacepenguin** [comment]
Ah perfect! Thanks for the help!
