### ISSUE TITLE
Code 31 when custom resolution/refresh rate is added to option.txt

### ISSUE THREAD

**Issue by G0ku737** [itsmikethetech/Virtual-Display-Driver#62]
I was trying to edit the option.txt file so that only the resolutions and refresh rates i need are present. I also added custom ones for my iPhone 15 Pro and iPad 6th Gen. 

The Driver only works with the original option.txt but not with the edited one. Neither when i add my resoltions to the end of the file without removing other resolution nor when i create a complete custom option.txt.

With the stock option.txt it works fine.

Here is an example of my custom option.txt file:

> 1
> 1280, 720, 60
> 1600, 900, 60
> 1920, 1080, 30
> 1920, 1080, 60
> 1920, 1080, 75
> 1920, 1080, 90
> 1920, 1080, 120
> 2038, 1536, 30
> 2038, 1536, 60
> 2556, 1179, 30
> 2556, 1179, 60
> 2556, 1179, 90
> 2556, 1179, 120
> 3840, 2160, 30
> 3840, 2160, 60

maybe i am making an error or custom resolutions are just not supported.
Regardless thank you for your work!

**Comment by JonnyTech** [comment]
Please try standard resolutions. For example change from `2038x1536` to `2048x1536`. And the iPhone 14/15 `2556x1179` will probably require a custom EDID so remove those and check. Look at the README for a link to an EDID generator.

**Comment by itsmikethetech** [comment]
Make sure there's an empty line at the end of the options.txt. It should work with any standard or non-standard resolution.

**Comment by G0ku737** [comment]
> Make sure there's an empty line at the end of the options.txt. It should work with any standard or non-standard resolution.

That was the issue. I had to ad free lines to the end of the file. Now all my resolution/refresh rate configs are working!

**Comment by itsmikethetech** [comment]
Great to hear!
