### ISSUE TITLE
3:2 aspect ratio crop

### ISSUE THREAD

**Issue by rszanto** [itsmikethetech/Virtual-Display-Driver#67]
Hi,

Currently 3:2 aspect ratio devices like the Pixel Slate get cropped when using 4K or HD resolutions.  Is there any way to include 3000 x 2000 as a resolution option? Thank you so much!

**Comment by itsmikethetech** [comment]
You can simply edit an existing resolution in C:/options.txt and reinstall the driver. Should show up. :)  Will see about adding it to the default list in the next update.

**Comment by bud3699** [comment]
Am I oki to close this issue ??
