### ISSUE TITLE
Virtual monitor installed but not in display settings

### ISSUE THREAD

**Issue by cubiclestorm** [itsmikethetech/Virtual-Display-Driver#69]
I'm running windows 10 with a 3090RTX.
Single physical monitor.

I installed the driver and the virtual monitor is showing in the device manager but no additional monitors are showing up in windows display settings.

**Comment by itsmikethetech** [comment]
Which version did you install?

**Comment by cubiclestorm** [comment]
> Which version did you install?

23.12.2

**Comment by cubiclestorm** [comment]
Ah I got the win 11 version
