### ISSUE TITLE
installed properly but no aditional displays found

### ISSUE THREAD

**Issue by shamirahim111** [itsmikethetech/Virtual-Display-Driver#7]
i am on w 10 ltsc  and installed your software which installed properly but nothing is shown by way of additional displays.

![Screenshot_20231114_110053](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/149858437/2464e102-d2ba-47fa-91bf-b35f74c747ea)

![hello](https://user-images.githubusercontent.com/149858437/280449517-1113f6f2-55ce-466c-9c9a-e5545785faca.png)

while investigating rustdesk virtual driver issue, i found your project and amyuni which actually worked and got installed so the problem is, why is your software installing but not showing and why isnt rustdesk getting installed in the first place.

https://github.com/rustdesk/rustdesk/issues/6280

**Comment by fufesou** [comment]
Please expand the "Monitors" list. Maybe you should also plug in a monitor.

**Comment by shamirahim111** [comment]
@fufesou i already have 1 actual monitor working.

![Screenshot_20231114_114305](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/149858437/b3914695-ea72-43b4-b441-861309432568)

**Comment by shamirahim111** [comment]
@fufesou here is what amyuni driver shows 
![Screenshot_20231114_114740](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/149858437/26ce960b-4381-41cf-bfc1-b1d674ae6314)

**Comment by fufesou** [comment]
I'm not sure I understand what you mean. But it looks like you installed the driver, but there is no virtual display.

You cannot see the virtual display. Because you did not have a virtual display monitor.

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/13586388/3a9df9a5-d8f7-40f9-af3a-d4e4a54a8293)

**Comment by shamirahim111** [comment]
@fufesou when i installed itsmikethetech driver, the driver was installed properly but no addiotional monitor was installed.

2. when i installed amyuni driver, THEN second monitor shows. 


currently only amyuni driver actually works properly.

**Comment by shamirahim111** [comment]
@fufesou yes. in the first screenshot that was only itsmikethetech driver installed and no monitor was showing

**Comment by fufesou** [comment]
I can't test this driver, I got a similar error.

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/13586388/817753cc-73e7-4928-9083-bfc34c789912)

**Comment by shamirahim111** [comment]
@fufesou strange. rustdesk driver gives me 31 code and itsmiketech installs  and vice versa for you.

**Comment by fufesou** [comment]
My mistake, I did not do this step

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/13586388/d0a390b1-77c2-4fad-841a-7d9b1a2132d1)

The driver works fine for me, and the monitor is there.

![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/13586388/4b4fff61-6936-43af-b2ad-fb80ee5d65d0)

**Comment by itsmikethetech** [comment]
Glad you got it working!

**Comment by itsmikethetech** [comment]
> i am on w 10 ltsc and installed your software which installed properly but nothing is shown by way of additional displays.
> 
> ![Screenshot_20231114_110053](https://private-user-images.githubusercontent.com/149858437/282672660-2464e102-d2ba-47fa-91bf-b35f74c747ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjIwMzIsIm5iZiI6MTcwMDg2MTczMiwicGF0aCI6Ii8xNDk4NTg0MzcvMjgyNjcyNjYwLTI0NjRlMTAyLWQyYmEtNDdmYS05MWJmLWIzNWY3NGM3NDdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNFQyMTM1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzVlZGViN2QzM2U4YzkzN2Y4NjdkYTg4NDYyNmE1MzkzZjAzOWUyZDI2ZTUzNzZkMjZkNzIyNTIwMTY2MjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x1ZK-WQ-bRiDNL6bcUiKqde2daz-ZoeFhlJRP7KItq4)
> 
> ![hello](https://user-images.githubusercontent.com/149858437/280449517-1113f6f2-55ce-466c-9c9a-e5545785faca.png)
> 
> while investigating rustdesk virtual driver issue, i found your project and amyuni which actually worked and got installed so the problem is, why is your software installing but not showing and why isnt rustdesk getting installed in the first place.
> 
> [rustdesk/rustdesk#6280](https://github.com/rustdesk/rustdesk/issues/6280)

Both likely use the same IDD driver. I would only use one at a time and see if they work. You can set multiple displays to come from one driver in the options.txt file.

**Comment by spikespaz** [comment]
I have this issue. What is the format of options.txt? it shows in device manager but there is nothing in windows settings.

**Comment by opencv4nodejs** [comment]
Download the Windows 10 version. This happened to me because I installed the latest Windows 11 drivers on Windows 10.

**Comment by SeryiBaran** [comment]
> I have this issue. What is the format of options.txt? it shows in device manager but there is nothing in windows settings.

+, same problem  =(
