### ISSUE TITLE
Monitor recognition issue - Windows 10

### ISSUE THREAD

**Issue by DavidCoq** [itsmikethetech/Virtual-Display-Driver#70]
I tried to install the driver, but Windows recognizes the device as a graphics card and not as a monitor because it doesn't give me the option to select the correct type. I'm using Windows 10 22H2 with an AMD Radeon R7 200 Series graphics card.

Is there any solution?

![01](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/7419884/d3271709-b0d4-4ff7-b2b4-3a7a9f30d707)
![02](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/7419884/e35e4e5a-0e56-41f6-8663-76551a5c7105)
![03](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/7419884/f69e2cb7-66b4-4073-ba46-c4ef4a3ce08a)

**Comment by kayti** [comment]
This is correct. It installs as GPU and add also monitor. But HDR version only works on Win11, not Win10.

**Comment by DavidCoq** [comment]
Thank you for your response. I thought I had downloaded the correct version.
You can close the ticket.
