### ISSUE TITLE
This device is not working properly because Windows cannot load the drivers required for this device. (Code 31)

### ISSUE THREAD

**Issue by dhowland** [itsmikethetech/Virtual-Display-Driver#71]
Windows can't load the driver, it gets the yellow warning icon with the following error:

`This device is not working properly because Windows cannot load the drivers required for this device. (Code 31)`

Running VDD.23.10.20.2 on Windows 10 22H2

**Comment by dhowland** [comment]
I read through #10 and tried a few things.  I uninstalled the driver, uninstalled the certificates, placed the install files in C:\IddSampleDriver, copied option.txt to options.txt, and reinstalled everything.  It seemed to work.

**Comment by bud3699** [comment]
Glad you got it working
