### ISSUE TITLE
Microphone just dies after reboot

### ISSUE THREAD

**Issue by TFB2024-Official** [itsmikethetech/Virtual-Display-Driver#74]
i rebooted my laptop only to find my mic is just. not there at all, its dead, Windows wont detect it
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/153972286/5f6ef74d-89f8-4036-a27c-1d2647b3b4a2)

**Comment by bud3699** [comment]
Does it show in device manager ?

**Comment by TFB2024-Official** [comment]
no, not at all, doesnt show in device manager, it is hidden and it shows this in the properties
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/153972286/1bd1d8bd-3440-467f-97b8-31c55fdcafab)

**Comment by TFB2024-Official** [comment]
translation:
currently, this hardware device isnt connected to the device (code 45)
its my internal mic, there is no connection to it

**Comment by bud3699** [comment]
Does this problem persist when disabling or uninstalling the driver ?

**Comment by TFB2024-Official** [comment]
i uninstalled the virtual display driver, still persists

**Comment by TFB2024-Official** [comment]
and no installing it doesnt help

**Comment by TFB2024-Official** [comment]
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/153972286/42d72042-4d34-45a0-a51a-1c16ff61bda4)
found the mic driver
no, its gone

**Comment by TFB2024-Official** [comment]
update: it works again
thanks for the help tho :D

**Comment by TFB2024-Official** [comment]
yes, I found the solution myself

**Comment by bud3699** [comment]
What was the solution in case it happens with anyone else ?
