### ISSUE TITLE
MONITOR HZ INFINITY

### ISSUE THREAD

**Issue by oriolprogamer712** [itsmikethetech/Virtual-Display-Driver#79]
REMOVE THE HERTZ LIMIT FROM THE SCREEN SO THAT YOU PUT MORE THAN 9999HZ HZ

**Comment by bud3699** [comment]
This isn't really an issue. And is highly not reccomended. If you'd like to add custom resolutions and refresh rates please do so at your own risk. This can be done by modifying options.txt file from when you installed the driver. 

Please be aware setting monitors above your gpus compatibility may causes system instability

**Comment by oriolprogamer712** [comment]
OK
