### ISSUE TITLE
I'm getting code 31 in the properties of the virtual display 

### ISSUE THREAD

**Issue by Pickymarker** [itsmikethetech/Virtual-Display-Driver#8]
I'm getting code 31 in the properties of the virtual display

**Comment by Pickymarker** [comment]
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/74084396/55ec5a7b-6887-4283-a76d-8928e9ad53b7)

**Comment by geshevk** [comment]
Had the same problem, it worked once I moved the folder to `C:\IddSampleDriver` and repeated the instructions. 🤷‍♂️
