### ISSUE TITLE
some resolutions and refreshrates are missing 

### ISSUE THREAD

**Issue by alexytomi** [itsmikethetech/Virtual-Display-Driver#83]
https://github.com/itsmikethetech/Virtual-Display-Driver/assets/60690056/1f5c8db4-4898-4fee-a6cd-e3366bfd7fee

[option.txt](https://github.com/itsmikethetech/Virtual-Display-Driver/files/15240089/option.txt)

**Comment by xuvvy** [comment]
The ones that are missing are not supported by the driver; this is particularly true for high refresh rates. You cannot run 8k resolution at 500 Hz.

**Comment by bud3699** [comment]
Possibly limited by edid. I'll close issue for now but I'll re-open if new light gets shed
