### ISSUE TITLE
refresh rate reverting back to 60Hz

### ISSUE THREAD

**Issue by albert-lmp** [itsmikethetech/Virtual-Display-Driver#87]
Using ROG ALLY, I set the resolution refresh rate manually to a higher Hz but after exiting a game it reverts back to 60Hz and I need to set it manually again.

**Comment by itsmikethetech** [comment]
Add the exact refresh rate to the resolution in options.txt and reinstall. Remove 60hz and add your preferred refresh rate. Should default to that from then on.

**Comment by albert-lmp** [comment]
Perfect, thanks!
