### ISSUE TITLE
Just install the driver but can not get more than 60Hz at 4K

### ISSUE THREAD

**Issue by aberthil** [itsmikethetech/Virtual-Display-Driver#93]
Is there a way to get to a higher display rate? How do I do this?

**Comment by lachyjp** [comment]
same issue. except anything over 1080p is limited to 60hz.

**Comment by alextoddslick** [comment]
change the FPS in options.txt from 60 - 240 (or whatever you want)

**Comment by sofmeright** [comment]
If you happen to be using sunshine for streaming this tool would allow you to set the [Width x Height + Hz] dynamically. It has Sunshine Integration that is well documented and easy to setup like QRes. It also has a GUI that will let you change every setting in these drivers without editing any configs. 

Virtual Display Driver: Wizard
A GUI tool that can integrate with other software such as Sunshine for efficient manipulation (Install / Uninstall / Reload / Configure) of Indirect Display Driver Sample (IddSample) implementations like the HDR capable [Virtual Display Driver from itsmikethetech](https://github.com/itsmikethetech/Virtual-Display-Driver) that works on Windows 10/11. This installer/configuration tool is intended to provide a more elegant solution in place of needing to edit configs or use Device Manger for driver installation.
https://github.com/sofmeright/VirtualDisplayDriver_Wizard

![PPIT-IddSample_Wiz-SS_GUI_Advanced](https://github.com/user-attachments/assets/ddfc6e7c-cdb2-468b-904d-3c80b5113dbf)
