### ISSUE TITLE
15360 x 4320

### ISSUE THREAD

**Issue by jamadir** [itsmikethetech/Virtual-Display-Driver#99]
Hello!

I use the virtual monitor to create screenshots of the contents of an industrial application.
Sadly, the maximum resolution of 8 k vertical is still not enough to capture larger projects.
Is it possible to add another resolution of 15360 x 4320 pixels?

Greetings
Jannes

**Comment by Dark1886** [comment]
Can you edit the Option.txt file to have this resolution?

**Comment by bud3699** [comment]
You can try, but whether or not it will work, is another question

**Comment by itsmikethetech** [comment]
It's possible, yes.
